services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/ComfyUI/output
      - ./user:/ComfyUI/user
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    ports:
      - "8188:8188"

