services:
  minimal:
    build:
      context: .
      dockerfile: Dockerfile.minimal
      tags:
        - l125/comfyui-for-dify:0.3.3-minimal
    volumes:
      - ./models:/ComfyUI/models
      - ./output:/ComfyUI/output
      - ./user:/ComfyUI/user
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
  cu118:
    build:
      context: .
      dockerfile: Dockerfile.cu118
      tags:
        - l125/comfyui-for-dify:0.3.3-cu118
    volumes:
      - ./models:/ComfyUI/models
      - ./output:/ComfyUI/output
      - ./user:/ComfyUI/user
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
  cu129:
    build:
      context: .
      dockerfile: Dockerfile.cu129
      tags:
        - l125/comfyui-for-dify:0.3.3-cu129
    volumes:
      - ./models:/ComfyUI/models
      - ./output:/ComfyUI/output
      - ./user:/ComfyUI/user
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
  cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
      tags:
        - l125/comfyui-for-dify:0.3.3-cpu
    volumes:
      - ./models:/ComfyUI/models
      - ./output:/ComfyUI/output
      - ./user:/ComfyUI/user
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
