services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./models:/ComfyUI/models
      - ./output:/ComfyUI/output
      - ./custom_nodes:/ComfyUI/custom_nodes
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    ports:
      - "8188:8188"
