FROM docker.io/python:3.12-slim

RUN apt update; apt install -y git curl
RUN curl -sL -o - https://github.com/comfyanonymous/ComfyUI/archive/refs/tags/v0.3.59.tar.gz | tar zxvf - && mv /ComfyUI-0.3.59 /ComfyUI
RUN pip install -r /ComfyUI/requirements.txt

WORKDIR /ComfyUI/custom_nodes/
RUN git clone https://github.com/ServiceStack/comfy-asset-downloader.git comfy-asset-downloader/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["python3", "/ComfyUI/main.py", "--listen"]
