FROM docker.io/rocm/pytorch:rocm7.1_ubuntu24.04_py3.12_pytorch_release_2.9.1

RUN apt update; apt install -y git 
RUN pip install comfy-cli
RUN yes | comfy --workspace=/ComfyUI install --skip-torch-or-directml --version v0.3.76
RUN comfy tracking disable

RUN comfy node install comfy-asset-downloader

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["comfy", "launch", "--", "--listen"]
