FROM docker.io/python:3.12-slim

RUN apt update; apt install -y git libopencv-dev g++ ffmpeg
RUN pip install comfy-cli
RUN yes | comfy --workspace=/ComfyUI install --nvidia --version latest --cuda-version 11.8
RUN pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN comfy tracking disable

RUN pip install gitpython onnxruntime
RUN comfy node install comfy-asset-downloader
RUN comfy node install ComfyUI-DepthAnythingV2
RUN comfy node install ComfyUI-Depth-Pro
RUN comfy node install ComfyUI-ReActor
RUN comfy node install ComfyUI-VideoHelperSuite

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["python3", "/ComfyUI/main.py", "--listen"]
