FROM docker.io/python:3.12-slim

RUN apt update; apt install -y git libopencv-dev g++ ffmpeg
RUN pip install comfy-cli
RUN yes | comfy --workspace=/ComfyUI install --cpu --version latest
RUN comfy tracking disable

RUN pip install gitpython onnxruntime nunchaku
RUN comfy node install comfy-asset-downloader
RUN comfy node install ComfyUI-DepthAnythingV2
RUN comfy node install ComfyUI-Depth-Pro
RUN comfy node install ComfyUI-ReActor
RUN comfy node install ComfyUI-VideoHelperSuite
RUN comfy node registry-install ComfyUI-nunchaku

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["python3", "/ComfyUI/main.py", "--listen", "--cpu"]