FROM docker.io/python:3.12-slim

RUN apt update; apt install -y git 
RUN pip install comfy-cli
RUN yes | comfy --workspace=/ComfyUI install --nvidia --version latest
RUN comfy tracking disable

RUN comfy node install comfy-asset-downloader

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["comfy", "launch", "--", "--listen"]